### ISSUE TITLE
DigitalOcean

### ISSUE THREAD

**Issue by smalltalker55** [infrastructor/infrastructor#144]
I use DigitalOcean, not AWS.   How much work would it take to extend infrastructure to work with DigitalOcean?   I might be willing to do the work, but need advice.  Is there someone who can work with me (i.e. give advice) to step me through this?   I have a lot of experience with Groovy.   I tried to use nix-ops and like the idea of a provisioning system like infrastructure but haven't really used one.

Ralph Johnson - rjohnson.uiuc@gmail.com

**Comment by tiurikov** [comment]
Hi Ralph,

Do you want to have something similar to [AwsInventory](https://github.com/infrastructor/infrastructor/wiki/Inventory-Reference#aws-inventory), but for DigitalOcean? I.e. you would to be able to build a dynamic inventory from existing cloud state. Can you bring more details about your use case?

**Comment by smalltalker55** [comment]
No, I don't think so.    I just want to deploy on DigitalOcean.

My system has two kinds of processors, the servers, and the workers.   I am
in the process of automating the creation of the workers, and i don't think
I need infrastructor for that.    I need it for the servers.

My system has an nginx server that serves as a reverse proxy, an NFS
server, samba, zookeeper, kafka, openvpn, and a couple of programs I wrote
myself.   There is a login server that runs on tomcat.   In general, you
can think about there being one of each server, though in fact zookeeper
and kafka need to be replicated and I might need to replicate some others
for performance.     But right now, since I am in development and there is
little load, I am running all the servers on one machine.

I'd like to use infrastructor to describe the configuration of each server
and which physical machine it is on.   And I'd like to be able to scale
from one to a dozen physical machines just by small changes in the
infrastructor script.   From what I can tell, infrastructor should allow
that.

Also, there will only be one cluster at first, but I predict we will need a
European one in addition to the American one to keep European customers
happy.    And of course we will need development and test clusters as well
as operational ones.   Again, it seems like a system like infrastructor
should help with this.

Does this make sense?

-Ralph Johnson

**Comment by smalltalker55** [comment]
Maybe I do want something like AwsInventory.   I don't think I need to
build an inventory from existing cloud state, but it looks to me like
AwsInventory lets you define your inventory and then provision it, which is
more what I want to do.

In other words, I want to set the cloud state from my script, not read the
cloud state.

-Ralph

**Comment by tiurikov** [comment]
Thank you for the explanation!

So you want Infrastructor to create DigitalOcean VMs and then deploy required services via SSH. 
Frankly speaking, I initially planned to go in that direction, there is an experimental [ManagedAwsInventory](https://github.com/infrastructor/infrastructor/wiki/Inventory-Reference#managed-aws-inventory-experimental) which does VMs provisioning on AWS... 

Anyways *cloud provisioning* and *server provisioning* are two different things. Infrastructor by design is more about the last one - server provisioning. There is a way to define an inventory of machines and then connect to all of them to run what you want. *Cloud provisioning* usually includes not only VM management (create / read / update / delete):
* Virtual Network 
* Load Balancer
* DNS
* Firewall
* CDN
* Databases
* KeyVaults

and so on... Infrastructor does not do that. A proper implementation of a full featured cloud provisioning tool requires lots of efforts for development and maintenance. Either a major part of the resources can be managed by the tool or the game is not worth the candle. That is why Infrastructor has main focus on server configuration atm.

I can suggest you to have look at [Terraform](https://www.terraform.io/docs/providers/do/index.html) for the cloud resource management and integrate it with Infrastructor by utilizing [local-exec](https://www.terraform.io/docs/provisioners/local-exec.html). It could be a good synergy and you will get the best of both worlds. 

I hope that helps.

**Comment by smalltalker55** [comment]
Creating new VMs is easy in DigitalOcean, so I don't care whether that is
automated.    The part I want to automate is setting them up once they are
created.   The firewall, virtual network and database are all provided by
DigitalOcean.   A load balancer might be nice, but I was planning to do it
more or less manually.   Basically, looking at the load every day and
readjusting things every few months (or more often, if necessary) as needed.

My question is how much work will it take to get infrastructor to work with
DigitalOcean.   Or will it already work using ssh?

**Comment by tiurikov** [comment]
> Creating new VMs is easy in DigitalOcean, so I don't care whether that is
automated.    The part I want to automate is setting them up once they are
created.

> My question is how much work will it take to get infrastructor to work with
DigitalOcean.

You can start right away if you know public IPs, SSH user name and private key (or password) of the VMs. No additional support for DigitalOcean is required. Just define an inventory using that information. Then you can run configuration tasks on all of them, e.g.:
```groovy
inlineInventory {
  node id: 'your-host-1', host: 'ip-or-dns-name-of-host', username: 'your-ssh-user', keyfile: 'path-to-private-ssh-key'
  node id: 'your-host-2', host: 'ip-or-dns-name-of-host', username: 'your-ssh-user', keyfile: 'path-to-private-ssh-key'
  ... 
}.provision {
  // tasks are defined here 
  task name: "install docker", actions: {
    shell user: 'root', command: '''
      apt update
      apt install docker.io -y
      usermod -aG docker ubuntu
      sysctl -w vm.max_map_count=262144
    '''
  }
}
```

**Comment by tiurikov** [comment]
closing the issue due to inactivity
